
import logging
from flask import Flask, request, jsonify, render_template, url_for

app = Flask(__name__)

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

@app.before_request
def log_request_info():
    logger.info(f"Request: {request.method} {request.path} - Body: {request.get_json()} - Query: {request.args}")

# Placeholder for dynamically added routes
ROUTES = {}

def add_route(endpoint, methods, response):
    @app.route(endpoint, methods=methods)
    def dynamic_route():
        return jsonify(response)

# Dynamically add routes
add_route('/v1/projects/testing-project-three/locations/global/keyRings/testing-three/cryptoKeys', ['GET'], {'cryptoKeys': [{'name': 'projects/testing-project-three/locations/global/keyRings/testing/cryptoKeys/testing-three-demo-key', 'primary': {'name': 'projects/testing-project-three/locations/global/keyRings/testing/cryptoKeys/testing-three-demo-key/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}, {'name': 'projects/testing-project-three/locations/global/keyRings/testing/cryptoKeys/testing-three-demo-key-three', 'primary': {'name': 'projects/testing-project-three/locations/global/keyRings/testing/cryptoKeys/testing-three-demo-key-three/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}, {'name': 'projects/testing-project-three/locations/global/keyRings/testing/cryptoKeys/testing-three-demo-key-three', 'primary': {'name': 'projects/testing-project-three/locations/global/keyRings/testing/cryptoKeys/testing-three-demo-key-three/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}], 'totalSize': 3})
add_route('/v1/projects/testing-project-three/locations/australia-southeast2/keyRings/big-m-testing-three/cryptoKeys', ['GET'], {'cryptoKeys': [{'name': 'projects/testing-project-three/locations/australia-southeast2/keyRings/testing/cryptoKeys/big-m-testing-three-demo-key', 'primary': {'name': 'projects/testing-project-three/locations/australia-southeast2/keyRings/testing/cryptoKeys/big-m-testing-three-demo-key/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}, {'name': 'projects/testing-project-three/locations/australia-southeast2/keyRings/testing/cryptoKeys/big-m-testing-three-demo-key-three', 'primary': {'name': 'projects/testing-project-three/locations/australia-southeast2/keyRings/testing/cryptoKeys/big-m-testing-three-demo-key-three/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}, {'name': 'projects/testing-project-three/locations/australia-southeast2/keyRings/testing/cryptoKeys/big-m-testing-three-demo-key-three', 'primary': {'name': 'projects/testing-project-three/locations/australia-southeast2/keyRings/testing/cryptoKeys/big-m-testing-three-demo-key-three/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}], 'totalSize': 3})
add_route('/v1/projects/testing-project-three/locations/australia-southeast1/keyRings', ['GET'], {})
add_route('/v1/projects/testing-project-three/locations/global/keyRings', ['GET'], {'keyRings': [{'name': 'projects/testing-project-three/locations/global/keyRings/testing-three', 'createTime': '2022-02-02T02:02:02.02000000Z'}], 'totalSize': 1})
add_route('/v1/projects/testing-project-three/locations/australia-southeast2/keyRings', ['GET'], {'keyRings': [{'name': 'projects/testing-project-three/locations/australia-southeast2/keyRings/big-m-testing-three', 'createTime': '2022-02-02T02:02:02.02000000Z'}], 'totalSize': 1})
add_route('/v1/projects/testing-project-two/locations/global/keyRings/testing-two/cryptoKeys', ['GET'], {'cryptoKeys': [{'name': 'projects/testing-project-two/locations/global/keyRings/testing/cryptoKeys/testing-two-demo-key', 'primary': {'name': 'projects/testing-project-two/locations/global/keyRings/testing/cryptoKeys/testing-two-demo-key/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}, {'name': 'projects/testing-project-two/locations/global/keyRings/testing/cryptoKeys/testing-two-demo-key-two', 'primary': {'name': 'projects/testing-project-two/locations/global/keyRings/testing/cryptoKeys/testing-two-demo-key-two/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}, {'name': 'projects/testing-project-two/locations/global/keyRings/testing/cryptoKeys/testing-two-demo-key-three', 'primary': {'name': 'projects/testing-project-two/locations/global/keyRings/testing/cryptoKeys/testing-two-demo-key-three/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}], 'totalSize': 3})
add_route('/v1/projects/testing-project-two/locations/australia-southeast2/keyRings/big-m-testing-two/cryptoKeys', ['GET'], {'cryptoKeys': [{'name': 'projects/testing-project-two/locations/australia-southeast2/keyRings/testing/cryptoKeys/big-m-testing-two-demo-key', 'primary': {'name': 'projects/testing-project-two/locations/australia-southeast2/keyRings/testing/cryptoKeys/big-m-testing-two-demo-key/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}, {'name': 'projects/testing-project-two/locations/australia-southeast2/keyRings/testing/cryptoKeys/big-m-testing-two-demo-key-two', 'primary': {'name': 'projects/testing-project-two/locations/australia-southeast2/keyRings/testing/cryptoKeys/big-m-testing-two-demo-key-two/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}, {'name': 'projects/testing-project-two/locations/australia-southeast2/keyRings/testing/cryptoKeys/big-m-testing-two-demo-key-three', 'primary': {'name': 'projects/testing-project-two/locations/australia-southeast2/keyRings/testing/cryptoKeys/big-m-testing-two-demo-key-three/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}], 'totalSize': 3})
add_route('/v1/projects/testing-project-two/locations/australia-southeast1/keyRings', ['GET'], {})
add_route('/v1/projects/testing-project-two/locations/global/keyRings', ['GET'], {'keyRings': [{'name': 'projects/testing-project-two/locations/global/keyRings/testing-two', 'createTime': '2022-02-02T02:02:02.02000000Z'}], 'totalSize': 1})
add_route('/v1/projects/testing-project-two/locations/australia-southeast2/keyRings', ['GET'], {'keyRings': [{'name': 'projects/testing-project-two/locations/australia-southeast2/keyRings/big-m-testing-two', 'createTime': '2022-02-02T02:02:02.02000000Z'}], 'totalSize': 1})
add_route('/v1/projects/testing-project/locations/global/keyRings/testing/cryptoKeys', ['GET'], {'cryptoKeys': [{'name': 'projects/testing-project/locations/global/keyRings/testing/cryptoKeys/testing-demo-key', 'primary': {'name': 'projects/testing-project/locations/global/keyRings/testing/cryptoKeys/testing-demo-key/cryptoKeyVersions/6', 'state': 'ENABLED', 'createTime': '2024-05-22T14:00:00.000000000Z', 'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION', 'generateTime': '2024-05-22T14:00:00.000000000Z'}, 'purpose': 'ENCRYPT_DECRYPT', 'createTime': '2023-02-04T03:03:03.000000000Z', 'nextRotationTime': '2025-03-03T14:00:00.000000000Z', 'rotationPeriod': '7776000s', 'versionTemplate': {'protectionLevel': 'SOFTWARE', 'algorithm': 'GOOGLE_SYMMETRIC_ENCRYPTION'}, 'destroyScheduledDuration': '86400s'}], 'totalSize': 1})
add_route('/v1/projects/testing-project/locations/australia-southeast1/keyRings', ['GET'], {})
add_route('/v1/projects/testing-project/locations/global/keyRings', ['GET'], {'keyRings': [{'name': 'projects/testing-project/locations/global/keyRings/testing', 'createTime': '2022-02-02T02:02:02.02000000Z'}], 'totalSize': 1})
add_route('/projects/testing-project/zones/australia-southeast1-a/instances/000000001/getIamPolicy', ['GET'], {'etag': 'ACAB'})
add_route('/token', ['POST'], {'access_token': 'some-access-token', 'token_type': 'access_token', 'id_token': 'eyJhbGciOiJSUzI1NiIsImN0eSI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNjAzMzc2MDExLCJleHAiOjExNjI4NTY1MzY0LCJhdWQiOiJhdWQteCIsImlzcyI6Imdvb2dsZSIsInNjb3BlIjoiZ29vZ2xlYXBpcyJ9.g_MHGMGbRt0MZaOyKPA7zQNrYRDgabBJwEzUGlCHlWlidWnYSG9mo5YixHwk1AfeDsRTnxxyT9Ki1mSppamKbS_QHj-o54PMLibP6jcQV4aLxwug9cKbzIvQTndWPm41gBT4Bxfip4ZI9DZUtVZ4nv89reDdmZ_WLG_HuDw-3p4E5L_5iIJGGEnfyko8Da1LiHZg6tNGzpmMyjxUhocvUdM5iEHeppkLlGlu9Lw38UVxUCvskKy6WRCnLU7uCZxeoA-Ah8jg-Ie6IPdKm2UvqUflQbfG-Ga7LqzMxSVE_KvRD9_02mYZykjuWQiEAWqMYnBqK4TtoFfAZLTa1cFGvQ', 'expires_in': 3600})
add_route('/v1/projects/testing-project/aggregated/usableSubnetworks', ['GET'], {'subnetworks': [{'subnetwork': 'projects/testing-project/regions/australia-southeast1/subnetworks/sn-02', 'network': 'projects/testing-project/global/networks/vpc-01', 'ipCidrRange': '10.0.1.0/24'}, {'subnetwork': 'projects/testing-project/regions/australia-southeast1/subnetworks/sn-01', 'network': 'projects/testing-project/global/networks/vpc-01', 'ipCidrRange': '10.0.0.0/24'}]})
add_route('/v1/projects/another-project/aggregated/usableSubnetworks', ['GET'], {'subnetworks': [{'subnetwork': 'projects/another-project/regions/australia-southeast1/subnetworks/sn-02', 'network': 'projects/another-project/global/networks/vpc-01', 'ipCidrRange': '10.0.1.0/24'}, {'subnetwork': 'projects/another-project/regions/australia-southeast1/subnetworks/sn-01', 'network': 'projects/another-project/global/networks/vpc-01', 'ipCidrRange': '10.0.0.0/24'}]})
add_route('/v1/projects/yet-another-project/aggregated/usableSubnetworks', ['GET'], {'subnetworks': [{'subnetwork': 'projects/yet-another-project/regions/australia-southeast1/subnetworks/sn-02', 'network': 'projects/yet-another-project/global/networks/vpc-01', 'ipCidrRange': '10.0.1.0/24'}, {'subnetwork': 'projects/yet-another-project/regions/australia-southeast1/subnetworks/sn-01', 'network': 'projects/yet-another-project/global/networks/vpc-01', 'ipCidrRange': '10.0.0.0/24'}]})
add_route('/v1/projects/empty-project/aggregated/usableSubnetworks', ['GET'], {'subnetworks': []})
add_route('/projects/testing-project/zones/australia-southeast1-a/acceleratorTypes', ['GET'], {'kind': 'compute#acceleratorTypeList', 'id': 'projects/testing-project/zones/australia-southeast1-a/acceleratorTypes', 'items': [{'kind': 'compute#acceleratorType', 'id': '10010', 'creationTimestamp': '1969-12-31T16:00:00.000-08:00', 'name': 'nvidia-tesla-p4', 'description': 'NVIDIA Tesla P4', 'zone': 'https://www.googleapis.com/compute/beta/projects/testing-project/zones/australia-southeast1-a', 'selfLink': 'https://www.googleapis.com/compute/beta/projects/testing-project/zones/australia-southeast1-a/acceleratorTypes/nvidia-tesla-p4', 'maximumCardsPerInstance': 4}, {'kind': 'compute#acceleratorType', 'id': '10012', 'creationTimestamp': '1969-12-31T16:00:00.000-08:00', 'name': 'nvidia-tesla-p4-vws', 'description': 'NVIDIA Tesla P4 Virtual Workstation', 'zone': 'https://www.googleapis.com/compute/beta/projects/testing-project/zones/australia-southeast1-a', 'selfLink': 'https://www.googleapis.com/compute/beta/projects/testing-project/zones/australia-southeast1-a/acceleratorTypes/nvidia-tesla-p4-vws', 'maximumCardsPerInstance': 4}, {'kind': 'compute#acceleratorType', 'id': '10019', 'creationTimestamp': '1969-12-31T16:00:00.000-08:00', 'name': 'nvidia-tesla-t4', 'description': 'NVIDIA Tesla T4', 'zone': 'https://www.googleapis.com/compute/beta/projects/testing-project/zones/australia-southeast1-a', 'selfLink': 'https://www.googleapis.com/compute/beta/projects/testing-project/zones/australia-southeast1-a/acceleratorTypes/nvidia-tesla-t4', 'maximumCardsPerInstance': 4}, {'kind': 'compute#acceleratorType', 'id': '10020', 'creationTimestamp': '1969-12-31T16:00:00.000-08:00', 'name': 'nvidia-tesla-t4-vws', 'description': 'NVIDIA Tesla T4 Virtual Workstation', 'zone': 'https://www.googleapis.com/compute/beta/projects/testing-project/zones/australia-southeast1-a', 'selfLink': 'https://www.googleapis.com/compute/beta/projects/testing-project/zones/australia-southeast1-a/acceleratorTypes/nvidia-tesla-t4-vws', 'maximumCardsPerInstance': 4}], 'selfLink': 'https://www.googleapis.com/compute/beta/projects/testing-project/zones/australia-southeast1-a/acceleratorTypes'})
add_route('/projects/another-project/zones/australia-southeast1-a/acceleratorTypes', ['GET'], {'kind': 'compute#acceleratorTypeList', 'id': 'projects/another-project/zones/australia-southeast1-a/acceleratorTypes', 'items': [{'kind': 'compute#acceleratorType', 'id': '11010', 'creationTimestamp': '1969-12-31T16:00:00.000-08:00', 'name': 'nvidia-tesla-p4', 'description': 'NVIDIA Tesla P4', 'zone': 'https://www.googleapis.com/compute/beta/projects/another-project/zones/australia-southeast1-a', 'selfLink': 'https://www.googleapis.com/compute/beta/projects/another-project/zones/australia-southeast1-a/acceleratorTypes/nvidia-tesla-p4', 'maximumCardsPerInstance': 4}, {'kind': 'compute#acceleratorType', 'id': '11012', 'creationTimestamp': '1969-12-31T16:00:00.000-08:00', 'name': 'nvidia-tesla-p4-vws', 'description': 'NVIDIA Tesla P4 Virtual Workstation', 'zone': 'https://www.googleapis.com/compute/beta/projects/another-project/zones/australia-southeast1-a', 'selfLink': 'https://www.googleapis.com/compute/beta/projects/another-project/zones/australia-southeast1-a/acceleratorTypes/nvidia-tesla-p4-vws', 'maximumCardsPerInstance': 4}, {'kind': 'compute#acceleratorType', 'id': '11019', 'creationTimestamp': '1969-12-31T16:00:00.000-08:00', 'name': 'nvidia-tesla-t4', 'description': 'NVIDIA Tesla T4', 'zone': 'https://www.googleapis.com/compute/beta/projects/another-project/zones/australia-southeast1-a', 'selfLink': 'https://www.googleapis.com/compute/beta/projects/another-project/zones/australia-southeast1-a/acceleratorTypes/nvidia-tesla-t4', 'maximumCardsPerInstance': 4}, {'kind': 'compute#acceleratorType', 'id': '11020', 'creationTimestamp': '1969-12-31T16:00:00.000-08:00', 'name': 'nvidia-tesla-t4-vws', 'description': 'NVIDIA Tesla T4 Virtual Workstation', 'zone': 'https://www.googleapis.com/compute/beta/projects/another-project/zones/australia-southeast1-a', 'selfLink': 'https://www.googleapis.com/compute/beta/projects/another-project/zones/australia-southeast1-a/acceleratorTypes/nvidia-tesla-t4-vws', 'maximumCardsPerInstance': 4}], 'selfLink': 'https://www.googleapis.com/compute/beta/projects/another-project/zones/australia-southeast1-a/acceleratorTypes'})
add_route('/v3/projects/testproject:getIamPolicy', ['POST'], {'version': 1, 'etag': 'BwXdCzeFew0=', 'bindings': [{'role': 'roles/appengine.serviceAgent', 'members': ['serviceAccount:service-1231231231230@gcp-gae-service.iam.gserviceaccount.com']}, {'role': 'roles/cloudbuild.builds.builder', 'members': ['serviceAccount:1231231231230@cloudbuild.gserviceaccount.com']}, {'role': 'roles/cloudbuild.serviceAgent', 'members': ['serviceAccount:service-1231231231230@gcp-sa-cloudbuild.iam.gserviceaccount.com']}, {'role': 'roles/containerregistry.ServiceAgent', 'members': ['serviceAccount:service-1231231231230@containerregistry.iam.gserviceaccount.com']}, {'role': 'roles/editor', 'members': ['serviceAccount:testproject@appspot.gserviceaccount.com']}, {'role': 'roles/firebaserules.system', 'members': ['serviceAccount:service-1231231231230@firebase-rules.iam.gserviceaccount.com']}, {'role': 'roles/firestore.serviceAgent', 'members': ['serviceAccount:service-1231231231230@gcp-sa-firestore.iam.gserviceaccount.com']}, {'role': 'roles/owner', 'members': ['serviceAccount:testproject-provisioner@testproject.iam.gserviceaccount.com', 'user:joeblow@testorg.io', 'user:johnsmith@testorg.io']}, {'role': 'roles/pubsub.serviceAgent', 'members': ['serviceAccount:service-1231231231230@gcp-sa-pubsub.iam.gserviceaccount.com']}]})

if __name__ == '__main__':
    app.run(debug=True)
